{
    contact {
        phone
        email
        addressText
        addressCoords
        accessTime
    }
    categories(sort: "name:asc", limit: 999) {
        id
        name
        slug
        parent {
        id
        }
        children {
        id
        name
        slug
        img {
            url
        }
        }
        img {
        url
        }
    }
    manufacturers(sort: "name:asc", limit:999) {
        id
        name
        slug

        img {
        url
        }
    }
}